# Generated by Django 4.2.4 on 2023-09-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sellingprice', models.FloatField()),
                ('description', models.TextField()),
                ('discountedprice', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('dt', 'Dresses'), ('je', 'Jeans'), ('ja', 'Jackets'), ('sh', 'Shirts'), ('te', 'Tees')], max_length=3)),
                ('image', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
