# Generated by Django 4.2.4 on 2023-09-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dt', 'Dresses'), ('je', 'Jeans'), ('ja', 'Jackets'), ('sh', 'Shirts'), ('te', 'Tees'), ('wa', 'Watch'), ('su', 'Sunglass'), ('ca', 'Candles')], max_length=3),
        ),
    ]
