# Generated by Django 4.2.4 on 2023-09-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
